/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package celebrity.finder.test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.FileNotFoundException;
import java.io.IOException;

import org.junit.Test;

import celebrity.finder.CelebrityFinder;
import celebrity.finder.Data;
import celebrity.finder.FinderAlgorithm;

public class DemoTest {
    @Test
    public void testWithQueue() {
       int party[][] = Data.fromClass();
       
       CelebrityFinder celebrityFinder = new FinderAlgorithm();
       celebrityFinder.setParty(party);
       assertFalse(celebrityFinder.find()==0);
    }
    
    @Test
    public void testFileReading() {
      
      try {
         int party[][] = Data.fromResource("data.csv");
         CelebrityFinder celebrityFinder = new FinderAlgorithm();
         celebrityFinder.setParty(party);
         assertTrue(celebrityFinder.find()==7);
      } catch (FileNotFoundException e) {
         fail();
      } catch (IOException e) {
         fail();
      }
    }
}
